# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/isorrentino/dev/robotology-superbuild/src/bipedal-locomotion-framework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/isorrentino/dev/robotology-superbuild/src/bipedal-locomotion-framework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"BipedalLocomotionFramework\" \"Unspecified\" \"bin\" \"configuration\" \"dev\" \"runtime\" \"shlib\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/isorrentino/dev/robotology-superbuild/src/bipedal-locomotion-framework/CMakeFiles /home/isorrentino/dev/robotology-superbuild/src/bipedal-locomotion-framework/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/isorrentino/dev/robotology-superbuild/src/bipedal-locomotion-framework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named ContinuousDynamicalSystem

# Build rule for target.
ContinuousDynamicalSystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousDynamicalSystem
.PHONY : ContinuousDynamicalSystem

# fast build rule for target.
ContinuousDynamicalSystem/fast:
	$(MAKE) -f src/ContinuousDynamicalSystem/CMakeFiles/ContinuousDynamicalSystem.dir/build.make src/ContinuousDynamicalSystem/CMakeFiles/ContinuousDynamicalSystem.dir/build
.PHONY : ContinuousDynamicalSystem/fast

#=============================================================================
# Target rules for targets named TextLogging

# Build rule for target.
TextLogging: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TextLogging
.PHONY : TextLogging

# fast build rule for target.
TextLogging/fast:
	$(MAKE) -f src/TextLogging/CMakeFiles/TextLogging.dir/build.make src/TextLogging/CMakeFiles/TextLogging.dir/build
.PHONY : TextLogging/fast

#=============================================================================
# Target rules for targets named TextLoggingYarpImplementation

# Build rule for target.
TextLoggingYarpImplementation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TextLoggingYarpImplementation
.PHONY : TextLoggingYarpImplementation

# fast build rule for target.
TextLoggingYarpImplementation/fast:
	$(MAKE) -f src/TextLogging/YarpImplementation/CMakeFiles/TextLoggingYarpImplementation.dir/build.make src/TextLogging/YarpImplementation/CMakeFiles/TextLoggingYarpImplementation.dir/build
.PHONY : TextLoggingYarpImplementation/fast

#=============================================================================
# Target rules for targets named VectorsCollection

# Build rule for target.
VectorsCollection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VectorsCollection
.PHONY : VectorsCollection

# fast build rule for target.
VectorsCollection/fast:
	$(MAKE) -f src/YarpUtilities/CMakeFiles/VectorsCollection.dir/build.make src/YarpUtilities/CMakeFiles/VectorsCollection.dir/build
.PHONY : VectorsCollection/fast

#=============================================================================
# Target rules for targets named YarpUtilities

# Build rule for target.
YarpUtilities: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 YarpUtilities
.PHONY : YarpUtilities

# fast build rule for target.
YarpUtilities/fast:
	$(MAKE) -f src/YarpUtilities/CMakeFiles/YarpUtilities.dir/build.make src/YarpUtilities/CMakeFiles/YarpUtilities.dir/build
.PHONY : YarpUtilities/fast

#=============================================================================
# Target rules for targets named ParametersHandler

# Build rule for target.
ParametersHandler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ParametersHandler
.PHONY : ParametersHandler

# fast build rule for target.
ParametersHandler/fast:
	$(MAKE) -f src/ParametersHandler/CMakeFiles/ParametersHandler.dir/build.make src/ParametersHandler/CMakeFiles/ParametersHandler.dir/build
.PHONY : ParametersHandler/fast

#=============================================================================
# Target rules for targets named ParametersHandlerYarpImplementation

# Build rule for target.
ParametersHandlerYarpImplementation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ParametersHandlerYarpImplementation
.PHONY : ParametersHandlerYarpImplementation

# fast build rule for target.
ParametersHandlerYarpImplementation/fast:
	$(MAKE) -f src/ParametersHandler/YarpImplementation/CMakeFiles/ParametersHandlerYarpImplementation.dir/build.make src/ParametersHandler/YarpImplementation/CMakeFiles/ParametersHandlerYarpImplementation.dir/build
.PHONY : ParametersHandlerYarpImplementation/fast

#=============================================================================
# Target rules for targets named ParametersHandlerTomlImplementation

# Build rule for target.
ParametersHandlerTomlImplementation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ParametersHandlerTomlImplementation
.PHONY : ParametersHandlerTomlImplementation

# fast build rule for target.
ParametersHandlerTomlImplementation/fast:
	$(MAKE) -f src/ParametersHandler/TomlImplementation/CMakeFiles/ParametersHandlerTomlImplementation.dir/build.make src/ParametersHandler/TomlImplementation/CMakeFiles/ParametersHandlerTomlImplementation.dir/build
.PHONY : ParametersHandlerTomlImplementation/fast

#=============================================================================
# Target rules for targets named ContactDetectors

# Build rule for target.
ContactDetectors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContactDetectors
.PHONY : ContactDetectors

# fast build rule for target.
ContactDetectors/fast:
	$(MAKE) -f src/Contacts/CMakeFiles/ContactDetectors.dir/build.make src/Contacts/CMakeFiles/ContactDetectors.dir/build
.PHONY : ContactDetectors/fast

#=============================================================================
# Target rules for targets named Contacts

# Build rule for target.
Contacts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Contacts
.PHONY : Contacts

# fast build rule for target.
Contacts/fast:
	$(MAKE) -f src/Contacts/CMakeFiles/Contacts.dir/build.make src/Contacts/CMakeFiles/Contacts.dir/build
.PHONY : Contacts/fast

#=============================================================================
# Target rules for targets named RobotDynamicsEstimator

# Build rule for target.
RobotDynamicsEstimator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RobotDynamicsEstimator
.PHONY : RobotDynamicsEstimator

# fast build rule for target.
RobotDynamicsEstimator/fast:
	$(MAKE) -f src/Estimators/CMakeFiles/RobotDynamicsEstimator.dir/build.make src/Estimators/CMakeFiles/RobotDynamicsEstimator.dir/build
.PHONY : RobotDynamicsEstimator/fast

#=============================================================================
# Target rules for targets named FloatingBaseEstimators

# Build rule for target.
FloatingBaseEstimators: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FloatingBaseEstimators
.PHONY : FloatingBaseEstimators

# fast build rule for target.
FloatingBaseEstimators/fast:
	$(MAKE) -f src/Estimators/CMakeFiles/FloatingBaseEstimators.dir/build.make src/Estimators/CMakeFiles/FloatingBaseEstimators.dir/build
.PHONY : FloatingBaseEstimators/fast

#=============================================================================
# Target rules for targets named Estimators

# Build rule for target.
Estimators: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Estimators
.PHONY : Estimators

# fast build rule for target.
Estimators/fast:
	$(MAKE) -f src/Estimators/CMakeFiles/Estimators.dir/build.make src/Estimators/CMakeFiles/Estimators.dir/build
.PHONY : Estimators/fast

#=============================================================================
# Target rules for targets named System

# Build rule for target.
System: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 System
.PHONY : System

# fast build rule for target.
System/fast:
	$(MAKE) -f src/System/CMakeFiles/System.dir/build.make src/System/CMakeFiles/System.dir/build
.PHONY : System/fast

#=============================================================================
# Target rules for targets named SystemYarpImplementation

# Build rule for target.
SystemYarpImplementation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SystemYarpImplementation
.PHONY : SystemYarpImplementation

# fast build rule for target.
SystemYarpImplementation/fast:
	$(MAKE) -f src/System/YarpImplementation/CMakeFiles/SystemYarpImplementation.dir/build.make src/System/YarpImplementation/CMakeFiles/SystemYarpImplementation.dir/build
.PHONY : SystemYarpImplementation/fast

#=============================================================================
# Target rules for targets named Unicycle

# Build rule for target.
Unicycle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Unicycle
.PHONY : Unicycle

# fast build rule for target.
Unicycle/fast:
	$(MAKE) -f src/Planners/CMakeFiles/Unicycle.dir/build.make src/Planners/CMakeFiles/Unicycle.dir/build
.PHONY : Unicycle/fast

#=============================================================================
# Target rules for targets named Planners

# Build rule for target.
Planners: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Planners
.PHONY : Planners

# fast build rule for target.
Planners/fast:
	$(MAKE) -f src/Planners/CMakeFiles/Planners.dir/build.make src/Planners/CMakeFiles/Planners.dir/build
.PHONY : Planners/fast

#=============================================================================
# Target rules for targets named ContactModels

# Build rule for target.
ContactModels: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContactModels
.PHONY : ContactModels

# fast build rule for target.
ContactModels/fast:
	$(MAKE) -f src/ContactModels/CMakeFiles/ContactModels.dir/build.make src/ContactModels/CMakeFiles/ContactModels.dir/build
.PHONY : ContactModels/fast

#=============================================================================
# Target rules for targets named RobotInterface

# Build rule for target.
RobotInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RobotInterface
.PHONY : RobotInterface

# fast build rule for target.
RobotInterface/fast:
	$(MAKE) -f src/RobotInterface/CMakeFiles/RobotInterface.dir/build.make src/RobotInterface/CMakeFiles/RobotInterface.dir/build
.PHONY : RobotInterface/fast

#=============================================================================
# Target rules for targets named PerceptionInterfaceYarpImplementation

# Build rule for target.
PerceptionInterfaceYarpImplementation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PerceptionInterfaceYarpImplementation
.PHONY : PerceptionInterfaceYarpImplementation

# fast build rule for target.
PerceptionInterfaceYarpImplementation/fast:
	$(MAKE) -f src/RobotInterface/YarpImplementation/CMakeFiles/PerceptionInterfaceYarpImplementation.dir/build.make src/RobotInterface/YarpImplementation/CMakeFiles/PerceptionInterfaceYarpImplementation.dir/build
.PHONY : PerceptionInterfaceYarpImplementation/fast

#=============================================================================
# Target rules for targets named RobotInterfaceYarpImplementation

# Build rule for target.
RobotInterfaceYarpImplementation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RobotInterfaceYarpImplementation
.PHONY : RobotInterfaceYarpImplementation

# fast build rule for target.
RobotInterfaceYarpImplementation/fast:
	$(MAKE) -f src/RobotInterface/YarpImplementation/CMakeFiles/RobotInterfaceYarpImplementation.dir/build.make src/RobotInterface/YarpImplementation/CMakeFiles/RobotInterfaceYarpImplementation.dir/build
.PHONY : RobotInterfaceYarpImplementation/fast

#=============================================================================
# Target rules for targets named Math

# Build rule for target.
Math: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Math
.PHONY : Math

# fast build rule for target.
Math/fast:
	$(MAKE) -f src/Math/CMakeFiles/Math.dir/build.make src/Math/CMakeFiles/Math.dir/build
.PHONY : Math/fast

#=============================================================================
# Target rules for targets named TSID

# Build rule for target.
TSID: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TSID
.PHONY : TSID

# fast build rule for target.
TSID/fast:
	$(MAKE) -f src/TSID/CMakeFiles/TSID.dir/build.make src/TSID/CMakeFiles/TSID.dir/build
.PHONY : TSID/fast

#=============================================================================
# Target rules for targets named PerceptionFeatures

# Build rule for target.
PerceptionFeatures: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PerceptionFeatures
.PHONY : PerceptionFeatures

# fast build rule for target.
PerceptionFeatures/fast:
	$(MAKE) -f src/Perception/CMakeFiles/PerceptionFeatures.dir/build.make src/Perception/CMakeFiles/PerceptionFeatures.dir/build
.PHONY : PerceptionFeatures/fast

#=============================================================================
# Target rules for targets named IK

# Build rule for target.
IK: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IK
.PHONY : IK

# fast build rule for target.
IK/fast:
	$(MAKE) -f src/IK/CMakeFiles/IK.dir/build.make src/IK/CMakeFiles/IK.dir/build
.PHONY : IK/fast

#=============================================================================
# Target rules for targets named SimplifiedModelControllers

# Build rule for target.
SimplifiedModelControllers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SimplifiedModelControllers
.PHONY : SimplifiedModelControllers

# fast build rule for target.
SimplifiedModelControllers/fast:
	$(MAKE) -f src/SimplifiedModelControllers/CMakeFiles/SimplifiedModelControllers.dir/build.make src/SimplifiedModelControllers/CMakeFiles/SimplifiedModelControllers.dir/build
.PHONY : SimplifiedModelControllers/fast

#=============================================================================
# Target rules for targets named FloatingBaseEstimatorDevice

# Build rule for target.
FloatingBaseEstimatorDevice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FloatingBaseEstimatorDevice
.PHONY : FloatingBaseEstimatorDevice

# fast build rule for target.
FloatingBaseEstimatorDevice/fast:
	$(MAKE) -f devices/FloatingBaseEstimatorDevice/CMakeFiles/FloatingBaseEstimatorDevice.dir/build.make devices/FloatingBaseEstimatorDevice/CMakeFiles/FloatingBaseEstimatorDevice.dir/build
.PHONY : FloatingBaseEstimatorDevice/fast

#=============================================================================
# Target rules for targets named RobotDynamicsEstimatorDevice

# Build rule for target.
RobotDynamicsEstimatorDevice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RobotDynamicsEstimatorDevice
.PHONY : RobotDynamicsEstimatorDevice

# fast build rule for target.
RobotDynamicsEstimatorDevice/fast:
	$(MAKE) -f devices/RobotDynamicsEstimatorDevice/CMakeFiles/RobotDynamicsEstimatorDevice.dir/build.make devices/RobotDynamicsEstimatorDevice/CMakeFiles/RobotDynamicsEstimatorDevice.dir/build
.PHONY : RobotDynamicsEstimatorDevice/fast

#=============================================================================
# Target rules for targets named YarpRobotLoggerDevice

# Build rule for target.
YarpRobotLoggerDevice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 YarpRobotLoggerDevice
.PHONY : YarpRobotLoggerDevice

# fast build rule for target.
YarpRobotLoggerDevice/fast:
	$(MAKE) -f devices/YarpRobotLoggerDevice/CMakeFiles/YarpRobotLoggerDevice.dir/build.make devices/YarpRobotLoggerDevice/CMakeFiles/YarpRobotLoggerDevice.dir/build
.PHONY : YarpRobotLoggerDevice/fast

#=============================================================================
# Target rules for targets named tiny-process-library

# Build rule for target.
tiny-process-library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiny-process-library
.PHONY : tiny-process-library

# fast build rule for target.
tiny-process-library/fast:
	$(MAKE) -f _deps/tiny_process_library-build/CMakeFiles/tiny-process-library.dir/build.make _deps/tiny_process_library-build/CMakeFiles/tiny-process-library.dir/build
.PHONY : tiny-process-library/fast

#=============================================================================
# Target rules for targets named VectorsCollectionWrapper

# Build rule for target.
VectorsCollectionWrapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VectorsCollectionWrapper
.PHONY : VectorsCollectionWrapper

# fast build rule for target.
VectorsCollectionWrapper/fast:
	$(MAKE) -f devices/VectorsCollectionWrapper/CMakeFiles/VectorsCollectionWrapper.dir/build.make devices/VectorsCollectionWrapper/CMakeFiles/VectorsCollectionWrapper.dir/build
.PHONY : VectorsCollectionWrapper/fast

#=============================================================================
# Target rules for targets named pybind11_blf

# Build rule for target.
pybind11_blf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pybind11_blf
.PHONY : pybind11_blf

# fast build rule for target.
pybind11_blf/fast:
	$(MAKE) -f bindings/python/CMakeFiles/pybind11_blf.dir/build.make bindings/python/CMakeFiles/pybind11_blf.dir/build
.PHONY : pybind11_blf/fast

#=============================================================================
# Target rules for targets named joint-position-tracking

# Build rule for target.
joint-position-tracking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 joint-position-tracking
.PHONY : joint-position-tracking

# fast build rule for target.
joint-position-tracking/fast:
	$(MAKE) -f utilities/joint-position-tracking/CMakeFiles/joint-position-tracking.dir/build.make utilities/joint-position-tracking/CMakeFiles/joint-position-tracking.dir/build
.PHONY : joint-position-tracking/fast

#=============================================================================
# Target rules for targets named joint-trajectory-player

# Build rule for target.
joint-trajectory-player: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 joint-trajectory-player
.PHONY : joint-trajectory-player

# fast build rule for target.
joint-trajectory-player/fast:
	$(MAKE) -f utilities/joint-trajectory-player/CMakeFiles/joint-trajectory-player.dir/build.make utilities/joint-trajectory-player/CMakeFiles/joint-trajectory-player.dir/build
.PHONY : joint-trajectory-player/fast

#=============================================================================
# Target rules for targets named mas-imu-test

# Build rule for target.
mas-imu-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mas-imu-test
.PHONY : mas-imu-test

# fast build rule for target.
mas-imu-test/fast:
	$(MAKE) -f utilities/mas-imu-test/CMakeFiles/mas-imu-test.dir/build.make utilities/mas-imu-test/CMakeFiles/mas-imu-test.dir/build
.PHONY : mas-imu-test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... uninstall"
	@echo "... ContinuousDynamicalSystem"
	@echo "... TextLogging"
	@echo "... TextLoggingYarpImplementation"
	@echo "... VectorsCollection"
	@echo "... YarpUtilities"
	@echo "... ParametersHandler"
	@echo "... ParametersHandlerYarpImplementation"
	@echo "... ParametersHandlerTomlImplementation"
	@echo "... ContactDetectors"
	@echo "... Contacts"
	@echo "... RobotDynamicsEstimator"
	@echo "... FloatingBaseEstimators"
	@echo "... Estimators"
	@echo "... System"
	@echo "... SystemYarpImplementation"
	@echo "... Unicycle"
	@echo "... Planners"
	@echo "... ContactModels"
	@echo "... RobotInterface"
	@echo "... PerceptionInterfaceYarpImplementation"
	@echo "... RobotInterfaceYarpImplementation"
	@echo "... Math"
	@echo "... TSID"
	@echo "... PerceptionFeatures"
	@echo "... IK"
	@echo "... SimplifiedModelControllers"
	@echo "... FloatingBaseEstimatorDevice"
	@echo "... RobotDynamicsEstimatorDevice"
	@echo "... YarpRobotLoggerDevice"
	@echo "... tiny-process-library"
	@echo "... VectorsCollectionWrapper"
	@echo "... pybind11_blf"
	@echo "... joint-position-tracking"
	@echo "... joint-trajectory-player"
	@echo "... mas-imu-test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

