bipedal-locomotion-framework: BipedalLocomotion::DCMWalkingPipeline::Module Class Reference
BipedalLocomotion::DCMWalkingPipeline::Module Class Reference
Public Member Functions
double getPeriod () override
Get the period of the RFModule.
bool updateModule () override
Main function of the RFModule.
bool configure (yarp::os::ResourceFinder &rf) final
Configure the RFModule.
bool close () override
Close the RFModule.
bool homing () final
This allows you to put the robot in a home position for walking.
bool startWalking () final
Detailed Description
Definition at line 27 of file Module.h.
Member Function Documentation
close()
bool Module::close () override
Close the RFModule.
Returns
true in case of success and false otherwise.
Definition at line 249 of file Module.cpp.
References std::endl().
configure()
bool Module::configure (yarp::os::ResourceFinder & rf) final
Configure the RFModule.
Parameters
rf is the reference to a resource finder object
Returns
true in case of success and false otherwise.
Definition at line 95 of file Module.cpp.
References std::endl().
getPeriod()
double Module::getPeriod () override
Get the period of the RFModule.
Returns
the period of the module.
Definition at line 21 of file Module.cpp.
homing()
bool Module::homing () final
This allows you to put the robot in a home position for walking.
Returns
true in case of success and false otherwise.
Definition at line 260 of file Module.cpp.
References std::endl().
updateModule()
bool Module::updateModule () override
Main function of the RFModule.
Returns
true in case of success and false otherwise.
Definition at line 26 of file Module.cpp.
References std::endl(), and std::this_thread::sleep_for().
The documentation for this class was generated from the following files:
DCMWalkingPipeline/include/BipedalLocomotion/DCMWalkingPipeline/Module.h
DCMWalkingPipeline/src/Module.cpp