bipedal-locomotion-framework: RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpHelper.h File Reference
YarpHelper.h File Reference
#include <memory>
#include <yarp/dev/PolyDriver.h>
#include <BipedalLocomotion/ParametersHandler/IParametersHandler.h>
Functions
std::shared_ptr< yarp::dev::PolyDriver > BipedalLocomotion::RobotInterface::constructYarpRobotDevice (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Helper function that can be used to build a RemoteControlBoardRemapper device.
Detailed Description
Authors
Giulio Romualdi
Copyright
2020 Istituto Italiano di Tecnologia (IIT). This software may be modified and distributed under the terms of the GNU Lesser General Public License v2.1 or any later version.
Definition in file YarpHelper.h.
Function Documentation
constructYarpRobotDevice()
std::shared_ptr< yarp::dev::PolyDriver > BipedalLocomotion::RobotInterface::constructYarpRobotDevice (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Helper function that can be used to build a RemoteControlBoardRemapper device.
Parameters
handler pointer to a parameter handler interface.
Note
the following parameters are required by the function
Parameter Name Type Description Mandatory
joints_list vector<string> List of the controlled joints Yes
remote_control_boards vector<string> List of the remote control boards associated to the joints Yes
robot_name string Name of the robot Yes
local_name string Name of the local application Yes
Returns
A shared_ptr to the PolyDriver. If one of the parameters is missing a nullptr is returned.
Definition at line 10 of file YarpHelper.cpp.
References BipedalLocomotion::RobotInterface::constructYarpRobotDevice(), std::endl(), and std::weak_ptr< T >::lock().
Referenced by BipedalLocomotion::RobotInterface::constructYarpRobotDevice().