/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_MASIMUTESTCOMMANDS_H
#define YARP_THRIFT_GENERATOR_SERVICE_MASIMUTESTCOMMANDS_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

/**
 * @file MasImuTestCommands.thrift
 * @authors Stefano Dafarra
 * @copyright 2019 Istituto Italiano di Tecnologia (IIT). This software may be modified and
 * distributed under the terms of the BSD-3-Clause license.
 */
class MasImuTestCommands :
        public yarp::os::Wire
{
public:
    // Constructor
    MasImuTestCommands();

    /**
     * Quits the module.
     */
    virtual void quit();

    /**
     * Call this method to start the test.
     * @return true/false in case of success/failure (for example if the preparation phase was not successfull);
     */
    virtual bool startTest();

    /**
     * Stop the test
     */
    virtual bool stopTest();

    /**
     * Print the results. This works only if the test has already been stopped.
     */
    virtual bool printResults();

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_MASIMUTESTCOMMANDS_H
